# Generated by Django 5.2.5 on 2025-08-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
